openapi: 3.0.1
info:
  title: Jar Account Service
  contact:
    email: antonrino.bosco@proton.me
  version: v1
paths:
  /jarAccounts:
    post:
      tags:
        - JarAccount
      summary: create a new jar account
      operationId: createJarAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewJarAccount'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JarAccount'
        400:
          description: Invalid status value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      tags:
        - JarAccount
      summary: retrives all jar accounts linked to a customerId or account
      operationId: getJarAccounts
      parameters:
        - in: query
          name: customerId
          description: customerId of the customer
          required: false
          schema:
            type: string
        - in: query
          name: linkedAccount
          description: accountId of the account
          required: false
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JarAccount'
        400:
          description: Invalid status value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /jarAccountSavings:
    post:
      tags:
        - JarAccount
      summary: create a new jar account
      operationId: saveIntoJarAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JarAccountSaving'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JarAccountTransaction'
        400:
          description: Invalid status value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    NewJarAccount:
      type: object
      properties:
        customerId:
          type: string
        linkedAccount:
          type: string
        currency:
          type: string
          enum:
            - EUR
        roundUp:
          type: string
          enum:
            - NEAREST_EUR
            - NEAREST_FIVE_EUR
            - NEAREST_TEN_EUR
          default: NEAREST_EUR
    JarAccount:
      type: object
      properties:
        jarAccountId:
          type: string
        customerId:
          type: string
        linkedAccount:
          type: string
        currency:
          type: string
          enum:
            - EUR
        roundUp:
          type: string
          enum:
            - NEAREST_EUR
            - NEAREST_FIVE_EUR
            - NEAREST_TEN_EUR
        balance:
          type: number
        status:
          type: string
          enum:
            - ENABLED
            - DISABLED
    JarAccountSaving:
      type: object
      properties:
        jarAccountId:
          type: string
        originalTransactionAmount:
          type: number
        bookingDate:
          type: string
          format: date
        valueDate:
          type: string
          format: date
    JarAccountTransaction:
      type: object
      properties:
        jarAccountTransactionId:
          type: string
        savingAmount:
          type: number
        originalTransactionAmount:
          type: number
        bookingDate:
          type: string
          format: date
        valueDate:
          type: string
          format: date
        narration:
          type: string
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string