openapi: 3.0.1
info:
  title: Jar Account Service
  contact:
    email: antonrino.bosco@proton.me
  version: v1
paths:
  /jarAccounts:
    post:
      tags:
        - JarAccount
      summary: create a new jar account
      operationId: createJarAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewJarAccount'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JarAccount'
        400:
          description: Invalid status value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    NewJarAccount:
      type: object
      properties:
        customerId:
          type: string
        linkedAccount:
          type: string
        currency:
          type: string
          enum:
            - EUR
        roundUp:
          type: string
          enum:
            - NEAREST_EUR
            - NEAREST_FIVE_EUR
            - NEAREST_TEN_EUR
          default: NEAREST_EUR
    JarAccount:
      type: object
      properties:
        jarAccountId:
          type: string
        customerId:
          type: string
        linkedAccount:
          type: string
        currency:
          type: string
          enum:
            - EUR
        roundUp:
          type: string
          enum:
            - NEAREST_EUR
            - NEAREST_FIVE_EUR
            - NEAREST_TEN_EUR
        status:
          type: string
          enum:
            - ENABLED
            - DISABLED
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string